name: build firmware

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PICO_SDK_FETCH_FROM_GIT: 1
  PICO_SDK_FETCH_FROM_GIT_TAG: 2.2.0

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi libnewlib-dev libnewlib-arm-none-eabi ninja-build cmake
    
    - name: build for Pico
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DPICO_BOARD=pico
        cmake --build build
        mv build/U2HTS.uf2 U2HTS_pico.uf2

    - name: build for Pico2
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DPICO_BOARD=pico2
        cmake --build build
        mv build/U2HTS.uf2 U2HTS_pico2.uf2

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}_RP2-${{ github.run_id }}
        path: |
          U2HTS_Pico.uf2
          U2HTS_Pico2.uf2
